// guests.js — updated from Excel upload
window.GUEST_LIST = [
  {"firstName": "Christian", "lastName": "Chang", "table": "1"},
  {"firstName": "Ryan", "lastName": "Liang", "table": "1"},
  {"firstName": "Cici", "lastName": "Liu", "table": "1", "meal": "Pescetarian"},
  {"firstName": "Ritch", "lastName": "Pilatan", "table": "1", "meal": "Grapes"},
  {"firstName": "Warren", "lastName": "Roque", "table": "1"},
  {"firstName": "Michelle", "lastName": "Tong", "table": "1"},
  {"firstName": "Joy", "lastName": "Torralba", "table": "1"},
  {"firstName": "Joe", "lastName": "Valookaran", "table": "1"},
  {"firstName": "Kendra", "lastName": "Yeung", "table": "1"},
  {"firstName": "Charmaine", "lastName": "Yu", "table": "1"},
  {"firstName": "Andrew", "lastName": "Chung", "table": "2", "meal": "raw apples, cherries, peaches, mangoes, pears, plums"},
  {"firstName": "Cynthia", "lastName": "Chung", "table": "2"},
  {"firstName": "Kelly", "lastName": "Chung", "table": "2"},
  {"firstName": "Mei Hua", "lastName": "Chung", "table": "2"},
  {"firstName": "Melanie", "lastName": "Chung", "table": "2", "meal": "Vegetarian/Vegan"},
  {"firstName": "Sterling", "lastName": "Chung", "table": "2", "seat": "Kid meal"},
  {"firstName": "Terence", "lastName": "Chung", "table": "2"},
  {"firstName": "Miho", "lastName": "Takahashi", "table": "2"},
  {"firstName": "Chris", "lastName": "Chen", "table": "3"},
  {"firstName": "Lin", "lastName": "Cheng", "table": "3"},
  {"firstName": "Binna", "lastName": "He", "table": "3"},
  {"firstName": "Chun Rong", "lastName": "He", "table": "3", "meal": "No Beef"},
  {"firstName": "Catherine", "lastName": "Lee", "table": "3"},
  {"firstName": "Charles", "lastName": "Lee", "table": "3"},
  {"firstName": "Elva", "lastName": "Ma", "table": "3"},
  {"firstName": "Zihan", "lastName": "Yang", "table": "3"},
  {"firstName": "Jin", "lastName": "Yian", "table": "3"},
  {"firstName": "Junjie", "lastName": "Zhao", "table": "3"},
  {"firstName": "Sam", "lastName": "Akhtar", "table": "4", "meal": "No pork"},
  {"firstName": "Amos", "lastName": "Lee", "table": "4"},
  {"firstName": "Brandon", "lastName": "Lee", "table": "4"},
  {"firstName": "Fredrick", "lastName": "Lee", "table": "4"},
  {"firstName": "Joletta", "lastName": "Lee", "table": "4"},
  {"firstName": "Ruth", "lastName": "Lee", "table": "4"},
  {"firstName": "Tesha", "lastName": "Moncrieffe", "table": "4"},
  {"firstName": "Christina", "lastName": "Chang", "table": "5"},
  {"firstName": "Zoey", "lastName": "Chau", "table": "5"},
  {"firstName": "Cynthia", "lastName": "Chiu", "table": "5"},
  {"firstName": "Will", "lastName": "Huang", "table": "5"},
  {"firstName": "Kent", "lastName": "Ko", "table": "5"},
  {"firstName": "Sheng", "lastName": "Lam", "table": "5"},
  {"firstName": "Jamie", "lastName": "McMahon", "table": "5"},
  {"firstName": "Lydia", "lastName": "Zhang", "table": "5"},
  {"firstName": "Carlo", "lastName": "Sacco", "table": "6"},
  {"firstName": "Lyon", "lastName": "Chan", "table": "6"},
  {"firstName": "Minah", "lastName": "Kim", "table": "6", "meal": "peaches and kiwis"},
  {"firstName": "Michael", "lastName": "Lam", "table": "6"},
  {"firstName": "Justine", "lastName": "Lee", "table": "6"},
  {"firstName": "Shirley", "lastName": "Lee", "table": "6"},
  {"firstName": "Fiona", "lastName": "Li", "table": "6"},
  {"firstName": "Josefine", "lastName": "Liao", "table": "6"},
  {"firstName": "Sabrina", "lastName": "Lu", "table": "6"},
  {"firstName": "Ashley", "lastName": "Wong", "table": "6"},
  {"firstName": "Leroy", "lastName": "Zhao", "table": "6"},
  {"firstName": "Cassandra", "lastName": "Lee", "table": "7"},
  {"firstName": "Crystal", "lastName": "Lee", "table": "7", "meal": "Vegetarian"},
  {"firstName": "Jonathan", "lastName": "Lee", "table": "7"},
  {"firstName": "KC", "lastName": "Lee", "table": "7"},
  {"firstName": "Adam", "lastName": "MacDonald", "table": "7", "seat": "Kid Meal"},
  {"firstName": "Andrew", "lastName": "MacDonald", "table": "7"},
  {"firstName": "Keira", "lastName": "MacDonald", "table": "7", "seat": "Kid Meal"},
  {"firstName": "Maria", "lastName": "Tan", "table": "7"},
  {"firstName": "Elizabeth", "lastName": "Cheung", "table": "8"},
  {"firstName": "Philip", "lastName": "Choi", "table": "8"},
  {"firstName": "Sharon", "lastName": "Lau", "table": "8"},
  {"firstName": "Tevin", "lastName": "Lu", "table": "8", "meal": "Lactose intolerance"},
  {"firstName": "Jeff", "lastName": "Miu", "table": "8"},
  {"firstName": "Justin", "lastName": "Miu", "table": "8"},
  {"firstName": "Albert", "lastName": "Tran", "table": "8", "meal": "Raw apples and tree nuts"},
  {"firstName": "Kenneka", "lastName": "Wu", "table": "8"},
  {"firstName": "MJ", "lastName": "Yeung", "table": "8"},
  {"firstName": "Aiman", "lastName": "Zaheer", "table": "8", "meal": "Halal if possible"},
  {"firstName": "Terence", "lastName": "Zeng", "table": "8"},
  {"firstName": "Lilian", "lastName": "Zhao", "table": "8"},
  {"firstName": "Alexis", "lastName": "Andruszko", "table": "9", "seat": "Kid meal & Needs Highchair"},
  {"firstName": "Dillon", "lastName": "Andruszko", "table": "9"},
  {"firstName": "Elizabeth", "lastName": "Andruszko", "table": "9", "meal": "Lactose free items please. No spicy foods."},
  {"firstName": "Anthony", "lastName": "Andryszko", "table": "9"},
  {"firstName": "Aria", "lastName": "Jordan", "table": "9"},
  {"firstName": "Justin", "lastName": "Jordan", "table": "9"},
  {"firstName": "Kavita", "lastName": "Khemraj", "table": "9", "meal": "Dairy, gluten, citrus, soy, sesame, nuts, nightshade vegetables, eggs, fish, masala, spicy foods, ONLY EATS CHICKEN"},
  {"firstName": "Brianne", "lastName": "Lee", "table": "9"},
  {"firstName": "Christopher", "lastName": "Lee", "table": "9"},
  {"firstName": "Jenny", "lastName": "Lee", "table": "9"},
  {"firstName": "Ken", "lastName": "Lee", "table": "9"},
  {"firstName": "Brendan", "lastName": "Chan", "table": "10", "meal": "Peanuts"},
  {"firstName": "Ho Juen", "lastName": "Chan", "table": "10"},
  {"firstName": "Sheila", "lastName": "Huang", "table": "10"},
  {"firstName": "Jason", "lastName": "Chung", "table": "10"},
  {"firstName": "Giselle", "lastName": "Wong", "table": "10"},
  {"firstName": "Kaia", "lastName": "Wong", "table": "10"},
  {"firstName": "Mia", "lastName": "Wong", "table": "10"},
  {"firstName": "Tiee", "lastName": "Wong", "table": "10"},
  {"firstName": "Valerie", "lastName": "Wong", "table": "10"},
  {"firstName": "Zeke", "lastName": "Wong", "table": "10", "seat": "Kid meal"},
  {"firstName": "Jeah", "lastName": "Banico", "table": "11"},
  {"firstName": "Suki", "lastName": "Cheung", "table": "11"},
  {"firstName": "John", "lastName": "Gavaran", "table": "11"},
  {"firstName": "Micheal", "lastName": "Seto", "table": "11"},
  {"firstName": "Amy", "lastName": "Lo", "table": "11", "meal": "No cashews/walnuts"},
  {"firstName": "Mia", "lastName": "Mihinay", "table": "11"},
  {"firstName": "Steven", "lastName": "Ou", "table": "11"},
  {"firstName": "Pam", "lastName": "Phy", "table": "11"},
  {"firstName": "Neil", "lastName": "Santos", "table": "11"},
  {"firstName": "Brian", "lastName": "Shiu", "table": "11"},
  {"firstName": "Erica", "lastName": "Tan", "table": "11"},
  {"firstName": "Tristan", "lastName": "Trieu", "table": "11"},
  {"firstName": "Tom", "lastName": "Chen", "table": "12"},
  {"firstName": "Steven", "lastName": "Khuu", "table": "12"},
  {"firstName": "Sarah", "lastName": "Lee", "table": "12", "meal": "Allergic to walnuts"},
  {"firstName": "Kevin", "lastName": "Liu", "table": "12"},
  {"firstName": "Ashlyn", "lastName": "Mark", "table": "12"},
  {"firstName": "Perry", "lastName": "Ni", "table": "12"},
  {"firstName": "James", "lastName": "Wen Shea", "table": "12"},
  {"firstName": "Raymond", "lastName": "Tantengco", "table": "12"},
  {"firstName": "Sara", "lastName": "Tonogai-Chen", "table": "12"},
  {"firstName": "Kimberly", "lastName": "Troung", "table": "12"},
  {"firstName": "Juliana", "lastName": "Chan", "table": "13"},
  {"firstName": "Owen", "lastName": "Chan", "table": "13"},
  {"firstName": "Steve", "lastName": "Chen", "table": "13"},
  {"firstName": "Max", "lastName": "Chu", "table": "13"},
  {"firstName": "Matthew", "lastName": "Lee", "table": "13"},
  {"firstName": "Jackie", "lastName": "Lu", "table": "13"},
  {"firstName": "Nicholas", "lastName": "Lu", "table": "13"},
  {"firstName": "Adam", "lastName": "Qiu", "table": "13"},
  {"firstName": "Samantha", "lastName": "Reid", "table": "13"},
  {"firstName": "Kye", "lastName": "Young", "table": "13"},
  {"firstName": "Andy", "lastName": "Zhao", "table": "13"},
  {"firstName": "Derek", "lastName": "", "table": "14"},
  {"firstName": "Hung", "lastName": "Hoang", "table": "14"},
  {"firstName": "Ngoc Hue", "lastName": "Huynh", "table": "14"},
  {"firstName": "Ngoc Linh", "lastName": "Huynh", "table": "14"},
  {"firstName": "Phuong", "lastName": "Huynh", "table": "14"},
  {"firstName": "To Ha", "lastName": "Huynh", "table": "14"},
  {"firstName": "Phuong", "lastName": "Le", "table": "14"},
  {"firstName": "Tinh", "lastName": "Le", "table": "14"},
  {"firstName": "Thi Che", "lastName": "Nguyen", "table": "14"},
  {"firstName": "Kim", "lastName": "Tran", "table": "14"},
  {"firstName": "Mui", "lastName": "Vong", "table": "14"},
  {"firstName": "Heather", "lastName": "Le", "table": "15", "seat": "No Meal"},
  {"firstName": "Jennifer", "lastName": "Le", "table": "15"},
  {"firstName": "Landon", "lastName": "Le", "table": "15", "seat": "Kid meal & Needs Highchair"},
  {"firstName": "Steven", "lastName": "Le", "table": "15"},
  {"firstName": "Lea", "lastName": "Rivera", "table": "15"},
  {"firstName": "Caitlyn", "lastName": "Tang", "table": "15", "meal": "Nuts, Seafood"},
  {"firstName": "Elizabeth", "lastName": "Tang", "table": "15"},
  {"firstName": "Eva", "lastName": "Voong", "table": "15", "seat": "Kid meal"},
  {"firstName": "James", "lastName": "Voong", "table": "15"},
  {"firstName": "Jamie", "lastName": "Voong", "table": "15", "seat": "Kid meal"},
  {"firstName": "Jett", "lastName": "Voong", "table": "15", "meal": "Nuts, Seafood", "seat": "Kid meal & Needs Highchair"},
  {"firstName": "Gabriella", "lastName": "Appiah", "table": "16"},
  {"firstName": "Kevin", "lastName": "Appiah", "table": "16"},
  {"firstName": "Lesley", "lastName": "Arber", "table": "16"},
  {"firstName": "Mike", "lastName": "Arber", "table": "16"},
  {"firstName": "Emmanuel", "lastName": "Danso Amofa", "table": "16"},
  {"firstName": "Jesse", "lastName": "Hayer", "table": "16"},
  {"firstName": "Madeleine", "lastName": "Hayer", "table": "16"},
  {"firstName": "Suraaj", "lastName": "Menon", "table": "16"},
  {"firstName": "Simran", "lastName": "Saini", "table": "16"},
  {"firstName": "Michelle", "lastName": "Chelladurai", "table": "17"},
  {"firstName": "Waylon", "lastName": "Chen", "table": "17"},
  {"firstName": "Max", "lastName": "Choi", "table": "17"},
  {"firstName": "Laura", "lastName": "Chu", "table": "17"},
  {"firstName": "Lance", "lastName": "Du", "table": "17"},
  {"firstName": "Richard", "lastName": "Sun", "table": "17"},
  {"firstName": "Tom", "lastName": "Sun", "table": "17"},
  {"firstName": "Richard", "lastName": "Sze", "table": "17", "meal": "Allergies to seafood and mangoes"},
  {"firstName": "Kristine", "lastName": "Yan", "table": "17", "meal": "Vegetarian"},
  {"firstName": "Jason", "lastName": "Yeung", "table": "17"},
  {"firstName": "Garret", "lastName": "Bulmer", "table": "18"},
  {"firstName": "Alex", "lastName": "Campagnolo", "table": "18"},
  {"firstName": "Erin", "lastName": "Clancy", "table": "18"},
  {"firstName": "Nathan", "lastName": "Koopman", "table": "18"},
  {"firstName": "Thomas", "lastName": "Martin", "table": "18"},
  {"firstName": "Anhi", "lastName": "Nguyen", "table": "18"},
  {"firstName": "Emma", "lastName": "Pirie", "table": "18"},
  {"firstName": "Josh", "lastName": "Roberts", "table": "18"},
  {"firstName": "Caleb", "lastName": "Seguin", "table": "18"},
  {"firstName": "Georgi", "lastName": "Williams", "table": "18"},
  {"firstName": "Raymond", "lastName": "Ang", "table": "19"},
  {"firstName": "Brandon", "lastName": "Chang", "table": "19"},
  {"firstName": "Kin", "lastName": "Chang", "table": "19", "meal": "Peach, mango, Logan and lychee"},
  {"firstName": "Maggie", "lastName": "Chang", "table": "19"},
  {"firstName": "Jennifer", "lastName": "Feng", "table": "19"},
  {"firstName": "Gary", "lastName": "Huang", "table": "19", "meal": "No Aloe"},
  {"firstName": "Jason", "lastName": "Lai", "table": "19"},
  {"firstName": "Eugene", "lastName": "Maninang", "table": "19"},
  {"firstName": "Ryan", "lastName": "Sunico", "table": "19"},
  {"firstName": "Allyson", "lastName": "Yang-Sunico", "table": "19", "meal": "Seafood, coconut, eggplant"},
  {"firstName": "Renee", "lastName": "Benavidez", "table": "20"},
  {"firstName": "Joseph", "lastName": "Hua", "table": "20", "meal": "avocado ,cantaloupe, honeydew"},
  {"firstName": "Thomas", "lastName": "Hua", "table": "20"},
  {"firstName": "Brian", "lastName": "Le", "table": "20"},
  {"firstName": "Charlie", "lastName": "Le", "table": "20"},
  {"firstName": "Jayden", "lastName": "Le", "table": "20"},
  {"firstName": "John", "lastName": "Le", "table": "20"},
  {"firstName": "Richard", "lastName": "Le", "table": "20"},
  {"firstName": "Victoria", "lastName": "Le", "table": "20"},
  {"firstName": "Brandon", "lastName": "Luc", "table": "20"},
  {"firstName": "Philip", "lastName": "Nguyen", "table": "20", "meal": "Shellfish/Fish"},
  {"firstName": "Victor", "lastName": "Nguyen", "table": "20"},
  {"firstName": "Luciano", "lastName": "Della Civita", "table": "21"},
  {"firstName": "Phouc", "lastName": "Hua", "table": "21"},
  {"firstName": "Jack", "lastName": "Ngo", "table": "21"},
  {"firstName": "Antoine", "lastName": "Nguyen", "table": "21"},
  {"firstName": "Van", "lastName": "Nguyen", "table": "21"},
  {"firstName": "Annie", "lastName": "Tang", "table": "21"},
  {"firstName": "Hang", "lastName": "Tang", "table": "21"},
  {"firstName": "Hung", "lastName": "Tang", "table": "21"},
  {"firstName": "Lien", "lastName": "Tang", "table": "21"},
  {"firstName": "Tom", "lastName": "Tang", "table": "21", "meal": "Talapia"},
  {"firstName": "Mai", "lastName": "Vo", "table": "21"},
  {"firstName": "Bradley", "lastName": "Bonner", "table": "22", "meal": "Eggs, Nuts"},
  {"firstName": "Sarah", "lastName": "Hua", "table": "22", "seat": "Kid meal"},
  {"firstName": "Cassidy", "lastName": "Le", "table": "22"},
  {"firstName": "Jack", "lastName": "Le", "table": "22", "seat": "Kid meal"},
  {"firstName": "Jayvan", "lastName": "Le", "table": "22", "meal": "Nuts", "seat": "Kid meal"},
  {"firstName": "Jessica", "lastName": "Le", "table": "22"},
  {"firstName": "Angelina", "lastName": "Tang", "table": "22"},
  {"firstName": "Lindsay", "lastName": "Tang", "table": "22", "meal": "peanuts, treenuts, cantelope, honeydew, watermelon, egg"},
  {"firstName": "Megan", "lastName": "Tang", "table": "22", "meal": "Walnut & Pecans"},
  {"firstName": "Sydney", "lastName": "Tang", "table": "22", "seat": "Kid meal"},
  {"firstName": "Vy", "lastName": "Tang", "table": "22"},
];
