// guests.js — auto-generated from seating chart
// To update: use the admin panel on the website, or replace this array.

window.GUEST_LIST = [
  // TABLE 1
  {"firstName":"Charles","lastName":"Lee","table":"1"},
  {"firstName":"Catherine","lastName":"Lee","table":"1"},
  {"firstName":"Grandma","lastName":"","table":"1"},
  {"firstName":"Binna","lastName":"He","table":"1"},
  {"firstName":"Chun Rong","lastName":"He","table":"1"},
  {"firstName":"Wen Hui","lastName":"Huang","table":"1"},
  {"firstName":"Fredrick","lastName":"Lee","table":"1"},
  {"firstName":"Jenny","lastName":"Lee","table":"1"},
  {"firstName":"Ken","lastName":"Lee","table":"1"},
  {"firstName":"Ki","lastName":"Rens","table":"1"},
  // TABLE 2
  {"firstName":"Cynthia","lastName":"Chung","table":"2"},
  {"firstName":"Mei Hua","lastName":"Chung","table":"2"},
  {"firstName":"Terence","lastName":"Chung","table":"2"},
  {"firstName":"Melanie","lastName":"Chung","table":"2"},
  {"firstName":"Miho","lastName":"Takahashi","table":"2"},
  {"firstName":"Andrew","lastName":"Chung","table":"2"},
  {"firstName":"Kelly","lastName":"Chung","table":"2"},
  {"firstName":"Sterling","lastName":"Chung","table":"2"},
  {"firstName":"Anthony","lastName":"Andryszko","table":"2"},
  {"firstName":"Elizabeth","lastName":"Andruszko","table":"2"},
  {"firstName":"Alexis","lastName":"Andruszko","table":"2"},
  // TABLE 3
  {"firstName":"Christina","lastName":"Chang","table":"3"},
  {"firstName":"Sheng","lastName":"Lam","table":"3"},
  {"firstName":"Zoey","lastName":"Chau","table":"3"},
  {"firstName":"Jamie","lastName":"McMahon","table":"3"},
  {"firstName":"Lydia","lastName":"Zhang","table":"3"},
  {"firstName":"Kent","lastName":"Ko","table":"3"},
  {"firstName":"Will","lastName":"Huang","table":"3"},
  {"firstName":"Cynthia","lastName":"Chiu","table":"3"},
  // TABLE 4
  {"firstName":"Ruth","lastName":"Lee","table":"4"},
  {"firstName":"Amos","lastName":"Lee","table":"4"},
  {"firstName":"Joletta","lastName":"Lee","table":"4"},
  {"firstName":"Brandon","lastName":"Lee","table":"4"},
  {"firstName":"Sam","lastName":"Akhtar","table":"4"},
  {"firstName":"Tesha","lastName":"Moncrieffe","table":"4"},
  {"firstName":"Christopher","lastName":"Lee","table":"4"},
  {"firstName":"Brianne","lastName":"Lee","table":"4"},
  {"firstName":"Justin","lastName":"Jordan","table":"4"},
  {"firstName":"Aria","lastName":"Jordan","table":"4"},
  // TABLE 5
  {"firstName":"Joe","lastName":"Valookaran","table":"5"},
  {"firstName":"Charmaine","lastName":"Yu","table":"5"},
  {"firstName":"Christian","lastName":"Chang","table":"5"},
  {"firstName":"Michelle","lastName":"Tong","table":"5"},
  {"firstName":"Ryan","lastName":"Liang","table":"5"},
  {"firstName":"Kendra","lastName":"Yeung","table":"5"},
  {"firstName":"Warren","lastName":"Roque","table":"5"},
  {"firstName":"Cici","lastName":"Liu","table":"5"},
  {"firstName":"Ritch","lastName":"Pilatan","table":"5"},
  {"firstName":"Joy","lastName":"Torralba","table":"5"},
  // TABLE 6
  {"firstName":"Josefine","lastName":"Liao","table":"6"},
  {"firstName":"Fiona","lastName":"Li","table":"6"},
  {"firstName":"Shirley","lastName":"Lee","table":"6"},
  {"firstName":"Justine","lastName":"Lee","table":"6"},
  {"firstName":"Carlos","lastName":"Acco","table":"6"},
  {"firstName":"Leroy","lastName":"Zhao","table":"6"},
  {"firstName":"Sabrina","lastName":"Lu","table":"6"},
  {"firstName":"Michael","lastName":"Lam","table":"6"},
  {"firstName":"Minah","lastName":"Kim","table":"6"},
  {"firstName":"Lyon","lastName":"Chan","table":"6"},
  {"firstName":"Ashley","lastName":"Wong","table":"6"},
  // TABLE 7
  {"firstName":"KC","lastName":"Lee","table":"7"},
  {"firstName":"Crystal","lastName":"Lee","table":"7"},
  {"firstName":"Cassandra","lastName":"MacDonald","table":"7"},
  {"firstName":"Andrew","lastName":"MacDonald","table":"7"},
  {"firstName":"Adam","lastName":"MacDonald","table":"7"},
  {"firstName":"Keira","lastName":"MacDonald","table":"7"},
  {"firstName":"Jonothan","lastName":"Lee","table":"7"},
  {"firstName":"Maria","lastName":"Tan","table":"7"},
  {"firstName":"Dilon","lastName":"Andruszko","table":"7"},
  {"firstName":"Kavita","lastName":"Khemraj","table":"7"},
  // TABLE 8
  {"firstName":"Justin","lastName":"Miu","table":"8"},
  {"firstName":"Lilian","lastName":"Zhao","table":"8"},
  {"firstName":"Aiman","lastName":"Zaheer","table":"8"},
  {"firstName":"Terence","lastName":"Zeng","table":"8"},
  {"firstName":"Jeff","lastName":"Miu","table":"8"},
  {"firstName":"MJ","lastName":"Yeung","table":"8"},
  {"firstName":"Albert","lastName":"Tran","table":"8"},
  {"firstName":"Sharon","lastName":"Lau","table":"8"},
  {"firstName":"Kenne Ka","lastName":"Wu","table":"8"},
  {"firstName":"Tevin","lastName":"Lu","table":"8"},
  {"firstName":"Philip","lastName":"Choi","table":"8"},
  {"firstName":"Liz","lastName":"Cheung","table":"8"},
  // TABLE 9
  {"firstName":"Chris","lastName":"Chen","table":"9"},
  {"firstName":"Elva","lastName":"Ma","table":"9"},
  {"firstName":"Zihan","lastName":"Yang","table":"9"},
  {"firstName":"Junjie","lastName":"Zhao","table":"9"},
  {"firstName":"Lin","lastName":"Cheng","table":"9"},
  {"firstName":"Jin","lastName":"Yian","table":"9"},
  {"firstName":"Phuong","lastName":"Le","table":"9"},
  {"firstName":"Hung","lastName":"Hoang","table":"9"},
  {"firstName":"Hung","lastName":"+1","table":"9"},
  // TABLE 10
  {"firstName":"Suki","lastName":"Cheung","table":"10"},
  {"firstName":"Brian","lastName":"Shiu","table":"10"},
  {"firstName":"Pam","lastName":"Phy","table":"10"},
  {"firstName":"Neil","lastName":"Santos","table":"10"},
  {"firstName":"Amy","lastName":"Lo","table":"10"},
  {"firstName":"Micheal","lastName":"Seto","table":"10"},
  {"firstName":"Tristan","lastName":"Trieu","table":"10"},
  {"firstName":"Mia","lastName":"Mihinay","table":"10"},
  {"firstName":"Erica","lastName":"Tan","table":"10"},
  {"firstName":"Steven","lastName":"Ou","table":"10"},
  // TABLE 11
  {"firstName":"Jason","lastName":"Chung","table":"11"},
  {"firstName":"Ho Juen","lastName":"Chan","table":"11"},
  {"firstName":"Sheila","lastName":"Chan","table":"11"},
  {"firstName":"Brendan","lastName":"Chan","table":"11"},
  {"firstName":"Tiee","lastName":"Wong","table":"11"},
  {"firstName":"Valerie","lastName":"Wong","table":"11"},
  {"firstName":"Mia","lastName":"Wong","table":"11"},
  {"firstName":"Giselle","lastName":"Wong","table":"11"},
  {"firstName":"Kaia","lastName":"Wong","table":"11"},
  {"firstName":"Zeke","lastName":"Wong","table":"11"},
  // TABLE 12
  {"firstName":"Jackie","lastName":"Lu","table":"12"},
  {"firstName":"Nicholas","lastName":"Lu","table":"12"},
  {"firstName":"Owen","lastName":"Chan","table":"12"},
  {"firstName":"Steve","lastName":"Chen","table":"12"},
  {"firstName":"Max","lastName":"Chu","table":"12"},
  {"firstName":"Andy","lastName":"Zhao","table":"12"},
  {"firstName":"Adam","lastName":"Qiu","table":"12"},
  {"firstName":"Matthew","lastName":"Lee","table":"12"},
  {"firstName":"Juliana","lastName":"Chan","table":"12"},
  {"firstName":"Samantha","lastName":"Reid","table":"12"},
  {"firstName":"Kye","lastName":"Young","table":"12"},
  // TABLE 13
  {"firstName":"Steven","lastName":"Khuu","table":"13"},
  {"firstName":"Kimberly","lastName":"Troung","table":"13"},
  {"firstName":"Kevin","lastName":"Liu","table":"13"},
  {"firstName":"Ashlyn","lastName":"Mark","table":"13"},
  {"firstName":"Tom","lastName":"Chen","table":"13"},
  {"firstName":"Sara","lastName":"Tonogai-Chen","table":"13"},
  {"firstName":"Perry","lastName":"Ni","table":"13"},
  {"firstName":"James Wen","lastName":"Shea","table":"13"},
  {"firstName":"Raymond","lastName":"Tantengco","table":"13"},
  {"firstName":"Sarah","lastName":"Lee","table":"13"},
  // TABLE 14
  {"firstName":"Jesse","lastName":"Hayer","table":"14"},
  {"firstName":"Madeleine","lastName":"Hayer","table":"14"},
  {"firstName":"Kevin","lastName":"Appiah","table":"14"},
  {"firstName":"Gabriella","lastName":"Appiah","table":"14"},
  {"firstName":"Suraaj","lastName":"Menon","table":"14"},
  {"firstName":"Simran","lastName":"Saini","table":"14"},
  {"firstName":"Lesley","lastName":"Arber","table":"14"},
  {"firstName":"Mike","lastName":"Arber","table":"14"},
  {"firstName":"Emmanuel","lastName":"Danso Amofa","table":"14"},
  // TABLE 15
  {"firstName":"Elizabeth","lastName":"Tang","table":"15"},
  {"firstName":"Caitlyn","lastName":"Tang","table":"15"},
  {"firstName":"James","lastName":"Voong","table":"15"},
  {"firstName":"Jamie","lastName":"Voong","table":"15"},
  {"firstName":"Jett","lastName":"Voong","table":"15"},
  {"firstName":"Eva","lastName":"Voong","table":"15"},
  {"firstName":"Steven","lastName":"Le","table":"15"},
  {"firstName":"Lea","lastName":"Rivera","table":"15"},
  {"firstName":"Heather","lastName":"Le","table":"15"},
  {"firstName":"Landon","lastName":"Le","table":"15"},
  // TABLE 16
  {"firstName":"Jason","lastName":"Yeung","table":"16"},
  {"firstName":"Kristine","lastName":"Yan","table":"16"},
  {"firstName":"Lance","lastName":"Du","table":"16"},
  {"firstName":"Laura","lastName":"Chu","table":"16"},
  {"firstName":"Waylon","lastName":"Chen","table":"16"},
  {"firstName":"Michelle","lastName":"Chelladurai","table":"16"},
  {"firstName":"Max","lastName":"Choi","table":"16"},
  {"firstName":"Richard","lastName":"Sun","table":"16"},
  {"firstName":"Tom","lastName":"Sun","table":"16"},
  {"firstName":"Richard","lastName":"Sze","table":"16"},
  // TABLE 17
  {"firstName":"Brandon","lastName":"Chang","table":"17"},
  {"firstName":"Danny","lastName":"Chang","table":"17"},
  {"firstName":"Kin","lastName":"Chang","table":"17"},
  {"firstName":"Maggie","lastName":"Chang","table":"17"},
  {"firstName":"Ivy","lastName":"Chang","table":"17"},
  {"firstName":"Raymond","lastName":"Ang","table":"17"},
  {"firstName":"Jason","lastName":"Lai","table":"17"},
  {"firstName":"Eugene","lastName":"Maninang","table":"17"},
  {"firstName":"Ryan","lastName":"Sunico","table":"17"},
  {"firstName":"Allyson","lastName":"Yang-Sunico","table":"17"},
  // TABLE 18
  {"firstName":"To Ha","lastName":"Huynh","table":"18"},
  {"firstName":"Thi Che","lastName":"Nguyen","table":"18"},
  {"firstName":"Ngoc Hue","lastName":"Huynh","table":"18"},
  {"firstName":"Ngoc Linh","lastName":"Huynh","table":"18"},
  {"firstName":"Tinh","lastName":"Le","table":"18"},
  {"firstName":"Mui","lastName":"Vong","table":"18"},
  {"firstName":"Kim","lastName":"Tran","table":"18"},
  {"firstName":"Phuong","lastName":"Huynh","table":"18"},
  // TABLE 19
  {"firstName":"Josh","lastName":"Roberts","table":"19"},
  {"firstName":"Georgi","lastName":"Williams","table":"19"},
  {"firstName":"Caleb","lastName":"Seguin","table":"19"},
  {"firstName":"Thomas","lastName":"Martin","table":"19"},
  {"firstName":"Nathan","lastName":"Koopman","table":"19"},
  {"firstName":"Anhi","lastName":"Nguyen","table":"19"},
  {"firstName":"Garret","lastName":"Bulmer","table":"19"},
  {"firstName":"Emma","lastName":"Pirie","table":"19"},
  {"firstName":"Alex","lastName":"Campagnolo","table":"19"},
  {"firstName":"Erin","lastName":"Clancy","table":"19"},
  // TABLE 20
  {"firstName":"Brandon","lastName":"Luc","table":"20"},
  {"firstName":"Victoria","lastName":"Le","table":"20"},
  {"firstName":"Richard","lastName":"Le","table":"20"},
  {"firstName":"Charlie","lastName":"Le","table":"20"},
  {"firstName":"Brian","lastName":"Le","table":"20"},
  {"firstName":"John","lastName":"Le","table":"20"},
  {"firstName":"Jayden","lastName":"Le","table":"20"},
  {"firstName":"Thomas","lastName":"Hua","table":"20"},
  {"firstName":"Joseph","lastName":"Hua","table":"20"},
  {"firstName":"Renee","lastName":"Benavidez","table":"20"},
  {"firstName":"Victor","lastName":"Nguyen","table":"20"},
  {"firstName":"Philip","lastName":"Nguyen","table":"20"},
  // TABLE 21
  {"firstName":"Hang","lastName":"Tang","table":"21"},
  {"firstName":"Luciano","lastName":"Della Civita","table":"21"},
  {"firstName":"Mai","lastName":"Vo","table":"21"},
  {"firstName":"Lien","lastName":"Tang","table":"21"},
  {"firstName":"Phouc","lastName":"Hua","table":"21"},
  {"firstName":"Tom","lastName":"Tang","table":"21"},
  {"firstName":"Jack","lastName":"Ngo","table":"21"},
  {"firstName":"Annie","lastName":"Tang","table":"21"},
  {"firstName":"Hung","lastName":"Tang","table":"21"},
  {"firstName":"Van","lastName":"Nguyen","table":"21"},
  {"firstName":"Antoine","lastName":"Nguyen","table":"21"},
  // TABLE 22
  {"firstName":"Jessica","lastName":"Le","table":"22"},
  {"firstName":"Cassidy","lastName":"Le","table":"22"},
  {"firstName":"Jack","lastName":"Le","table":"22"},
  {"firstName":"Jayvan","lastName":"Le","table":"22"},
  {"firstName":"Bradley","lastName":"Bonner","table":"22"},
  {"firstName":"Sarah","lastName":"Hua","table":"22"},
  {"firstName":"Lindsay","lastName":"Tang","table":"22"},
  {"firstName":"Vy","lastName":"Tang","table":"22"},
  {"firstName":"Megan","lastName":"Tang","table":"22"},
  {"firstName":"Sydney","lastName":"Tang","table":"22"},
  {"firstName":"Angelina","lastName":"Tang","table":"22"}
];
